imports:
    - { resource: ../../../etc/config/parameters.yml }
    
parameters:
    locale: en

twig:
    paths:
        '%kernel.root_dir%/templates/': styles
    globals:
        base_url: '/cms/web/install/install.php/'
        title: CMSFul Installer
framework:
    assets:
        packages:
            bower:
                base_path: '../assets/vendor'

    #esi:             ~
    translator:
        fallbacks: ["en"] 
        paths:
            - "%kernel.root_dir%/language/%locale%"
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:
        enabled: true
    csrf_protection: true
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #loaders: ['@CMS/Twig/Loaders/FileLoader']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true
    
