## YAML Template.
---

api.administration.content.projects:
    resource: "@CMS/Resources/config/routing/api/administration/content/projects.yml"
    
api.administration.content.pages:
    resource: "@CMS/Resources/config/routing/api/administration/content/pages.yml"
    
api.administration.content.posts:
    resource: "@CMS/Resources/config/routing/api/administration/content/posts.yml"
