admin.cache_clear:
    path: "%admin_link%/cache-clear"
    defaults: { _controller: CMS:Administration\Main:cacheClear }   
    
admin_panel:
    path: "%admin_link%/"
    defaults: { _controller: CMS:Administration\Main:index }
    