## YAML Template.
---
admin_content_add:
    path: "/add"
    defaults: {_controller: CMS:Administration\Content:add}

admin_content_edit:
    path: "/edit/{id}"
    defaults: {_controller: CMS:Administration\Content:edit}

admin_content_delete:
    path: "/delete/{id}"
    defaults: {_controller: CMS:Administration\Content:delete}
    
admin_content_manage:
    path: "/"
    defaults: {_controller: CMS:Administration\Content:index}