## YAML Template.
---
admin_role_add:
    path: "/add"
    defaults: {_controller: CMS:Administration\UserRole:add}

admin_role_edit:
    path: "/edit/{id}"
    defaults: {_controller: CMS:Administration\UserRole:edit}
    
admin_role_delete:
    path: "/delete/{id}"
    defaults: {_controller: CMS:Administration\UserRole:delete}

admin_role_manage:
    path: "/"
    defaults: {_controller: CMS:Administration\UserRole:index}