## YAML Template.
---

api.admin.general.settings.get:
    path: /settings
    defaults: {_controller: CMS:Administration\Api\General\Settings:get}
    methods: [GET]
    
api.admin.general.settings.post:
    path: /settings
    defaults: {_controller: CMS:Administration\Api\General\Settings:post}
    methods: [POST]