imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    admin_link: /admin
    base_url: ''
    cms.user.entity: 'CMS\Entity\User'

framework:
    assets:
        json_manifest_path: '%kernel.project_dir%/web/build/manifest.json'
        packages:
            includes:
                base_path: '../includes'
            bower:
                base_path: 'assets/vendor'
            portfolio:
                base_path: 'images/portfolio'
            gallery:
                base_path: 'images/gallery'
            avatar:
                base_path: 'images/avatar'
    #esi:             ~
    translator:
        fallbacks: ["en"]
        paths: 
            - "%kernel.root_dir%/language/"
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:
        enabled: true
    csrf_protection: true
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #loaders: ['@CMS/Twig/Loaders/FileLoader']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    form_theme:
        - "form/fields.html.twig"
    globals:
        base_dir: ""
        includes_dir: "/includes"
        base_url: "/app_dev.php/"
        admin_url: "/app_dev.php%admin_link%/"
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:sliding.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template
        
cms:
    db_driver: orm
    user_entity: 'CMS\Entity\User'
    news_entity: 'CMS\Entity\Article'

lexik_jwt_authentication:
    private_key_path: '%jwt_private_key_path%'
    public_key_path:  '%jwt_public_key_path%'
    pass_phrase:      '%jwt_key_pass_phrase%'
    token_ttl:        '%jwt_token_ttl%'