# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        CMS\Entity\User:
            algorithm: bcrypt
            cost: 15
            
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
    
    providers:
        in_memory:
            memory:
                users:
                    DemoAdmin:
                        password: DemoAdmin23
                        roles: ROLE_SUPER_ADMIN
                    
        cms.user_provider:
            entity:
                class: CMS:User
                property: username

        chain_provider:
            chain:
                providers: [ in_memory, cms.user_provider ]

    firewalls:
        api_login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            provider: cms.user_provider
            form_login:
                check_path:               /api/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        api:
            pattern:   ^/api
            stateless: true
            provider: cms.user_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: ^/login$
            anonymous: true

        main:
            remember_me:
                secret: '%secret%'
                lifetime: 2592000
                path: /
                secure: true
            provider: cms.user_provider
            pattern: ^/
            form_login:
                provider: cms.user_provider
                csrf_token_generator: security.csrf.token_manager
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    ~

    access_control:
        - { path: ^/api/login,  roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,        roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/login$,     roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register,   roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting,  roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile$,   roles: ROLE_USER }
        - { path: ^/admin/,     roles: ROLE_ADMIN }
        - { path: ^/$,          roles: ROLE_USER }
